// Unterscheidungszeichen (Ortskennzeichen) für den allgemeinen Fahrzeugverkehr in Deutschland mit Verwaltungsbezirk.
// Quelle: Liste der Kfz-Kennzeichen in Deutschland (Wikipedia, Stand Dezember 2023). Sonderkennzeichen für Bundes- und
// Landesbehörden (z. B. BD, BP, THW) sind bewusst nicht enthalten. Bei Änderungen der FZV hier nachpflegen.

export const DISTRICTS: Readonly<Record<string, string>> = {
  A: 'Stadt Augsburg und Landkreis Augsburg',
  AA: 'Ostalbkreis',
  AB: 'Stadt Aschaffenburg',
  ABG: 'Landkreis Altenburger Land',
  ABI: 'Landkreis Anhalt-Bitterfeld',
  AC: 'Städteregion Aachen',
  AE: 'Vogtlandkreis',
  AH: 'Kreis Borken',
  AIB: 'Landkreis Rosenheim',
  AIC: 'Landkreis Aichach-Friedberg',
  AK: 'Landkreis Altenkirchen (Westerwald)',
  ALF: 'Landkreis Hildesheim',
  ALZ: 'Landkreis Aschaffenburg',
  AM: 'Stadt Amberg',
  AN: 'Stadt Ansbach',
  ANA: 'Erzgebirgskreis',
  ANG: 'Landkreis Uckermark',
  ANK: 'Landkreis Vorpommern-Greifswald',
  AP: 'Landkreis Weimarer Land',
  APD: 'Landkreis Weimarer Land',
  ARN: 'Ilm-Kreis',
  ART: 'Kyffhäuserkreis',
  AS: 'Landkreis Amberg-Sulzbach',
  ASL: 'Salzlandkreis',
  ASZ: 'Erzgebirgskreis',
  AT: 'Landkreis Mecklenburgische Seenplatte',
  AU: 'Erzgebirgskreis',
  AUR: 'Landkreis Aurich',
  AW: 'Landkreis Ahrweiler',
  AZ: 'Landkreis Alzey-Worms',
  AZE: 'Landkreis Anhalt-Bitterfeld',
  'AÖ': 'Landkreis Altötting',
  B: 'Berlin',
  BA: 'Stadt und Landkreis Bamberg',
  BAD: 'Stadt Baden-Baden',
  BAR: 'Landkreis Barnim',
  BB: 'Landkreis Böblingen',
  BBG: 'Salzlandkreis',
  BC: 'Landkreis Biberach',
  BCH: 'Neckar-Odenwald-Kreis',
  BE: 'Kreis Warendorf',
  BED: 'Landkreis Mittelsachsen',
  BEL: 'Landkreis Potsdam-Mittelmark',
  BER: 'Landkreis Barnim',
  BF: 'Kreis Steinfurt',
  BGD: 'Landkreis Berchtesgadener Land',
  BGL: 'Landkreis Berchtesgadener Land',
  BH: 'Ortenaukreis; Landkreis Rastatt',
  BI: 'Stadt Bielefeld',
  BID: 'Landkreis Marburg-Biedenkopf',
  BIN: 'Landkreis Mainz-Bingen',
  BIR: 'Landkreis Birkenfeld',
  BIT: 'Eifelkreis Bitburg-Prüm',
  BIW: 'Landkreis Bautzen',
  BK: 'Rems-Murr-Kreis; Landkreis Schwäbisch Hall; Landkreis Börde',
  BKS: 'Landkreis Bernkastel-Wittlich',
  BL: 'Zollernalbkreis',
  BLB: 'Kreis Siegen-Wittgenstein',
  BLK: 'Burgenlandkreis',
  BM: 'Rhein-Erft-Kreis',
  BN: 'Stadt Bonn',
  BNA: 'Landkreis Leipzig',
  BO: 'Stadt Bochum',
  BOG: 'Landkreis Straubing-Bogen',
  BOH: 'Kreis Borken',
  BOR: 'Kreis Borken',
  BOT: 'Stadt Bottrop',
  BR: 'Landkreis Karlsruhe',
  BRA: 'Landkreis Wesermarsch',
  BRB: 'Stadt Brandenburg an der Havel',
  BRG: 'Landkreis Jerichower Land',
  BRK: 'Landkreis Bad Kissingen',
  BRL: 'Landkreis Goslar',
  BRV: 'Landkreis Rotenburg (Wümme)',
  BS: 'Stadt Braunschweig',
  BSB: 'Landkreis Osnabrück',
  BSK: 'Landkreis Oder-Spree',
  BT: 'Stadt und Landkreis Bayreuth',
  BTF: 'Landkreis Anhalt-Bitterfeld',
  BUL: 'Landkreis Amberg-Sulzbach; Landkreis Schwandorf',
  BZ: 'Landkreis Bautzen',
  'BÖ': 'Landkreis Börde',
  'BÜD': 'Wetteraukreis',
  'BÜR': 'Kreis Paderborn',
  'BÜS': 'Gemeinde Büsingen am Hochrhein',
  'BÜZ': 'Landkreis Rostock',
  C: 'Stadt Chemnitz',
  CA: 'Landkreis Oberspreewald-Lausitz',
  CAS: 'Kreis Recklinghausen',
  CB: 'Stadt Cottbus',
  CE: 'Landkreis Celle',
  CHA: 'Landkreis Cham',
  CLP: 'Landkreis Cloppenburg',
  CLZ: 'Landkreis Goslar',
  CO: 'Stadt und Landkreis Coburg',
  COC: 'Landkreis Cochem-Zell',
  COE: 'Kreis Coesfeld',
  CR: 'Landkreis Schwäbisch Hall',
  CUX: 'Landkreis Cuxhaven',
  CW: 'Landkreis Calw',
  D: 'Stadt Düsseldorf',
  DA: 'Stadt Darmstadt; Landkreis Darmstadt-Dieburg',
  DAH: 'Landkreis Dachau',
  DAN: 'Landkreis Lüchow-Dannenberg',
  DAU: 'Landkreis Vulkaneifel',
  DBR: 'Landkreis Rostock',
  DD: 'Stadt Dresden',
  DE: 'Stadt Dessau-Roßlau',
  DEG: 'Landkreis Deggendorf',
  DEL: 'Stadt Delmenhorst',
  DGF: 'Landkreis Dingolfing-Landau',
  DH: 'Landkreis Diepholz',
  DI: 'Landkreis Darmstadt-Dieburg',
  DIL: 'Lahn-Dill-Kreis',
  DIN: 'Kreis Wesel',
  DIZ: 'Rhein-Lahn-Kreis',
  DKB: 'Landkreis Ansbach',
  DL: 'Landkreis Mittelsachsen',
  DLG: 'Landkreis Dillingen an der Donau',
  DM: 'Landkreis Mecklenburgische Seenplatte',
  DN: 'Kreis Düren',
  DO: 'Stadt Dortmund',
  DON: 'Landkreis Donau-Ries',
  DS: 'Schwarzwald-Baar-Kreis',
  DT: 'Kreis Lippe',
  DU: 'Stadt Duisburg',
  DUD: 'Landkreis Göttingen',
  DW: 'Landkreis Sächsische Schweiz-Osterzgebirge',
  DZ: 'Landkreis Nordsachsen',
  'DÜW': 'Landkreis Bad Dürkheim',
  E: 'Stadt Essen',
  EA: 'Wartburgkreis',
  EB: 'Landkreis Nordsachsen',
  EBE: 'Landkreis Ebersberg',
  EBN: 'Landkreis Haßberge',
  EBS: 'Landkreis Bayreuth; Landkreis Forchheim; Landkreis Kulmbach',
  ECK: 'Kreis Rendsburg-Eckernförde',
  ED: 'Landkreis Erding',
  EE: 'Landkreis Elbe-Elster',
  EF: 'Stadt Erfurt',
  EG: 'Landkreis Rottal-Inn',
  EH: 'Landkreis Oder-Spree',
  EI: 'Landkreis Eichstätt',
  EIC: 'Landkreis Eichsfeld',
  EIL: 'Landkreis Mansfeld-Südharz',
  EIN: 'Landkreis Northeim',
  EIS: 'Saale-Holzland-Kreis',
  EL: 'Landkreis Emsland',
  EM: 'Landkreis Emmendingen',
  EMD: 'Stadt Emden',
  EMS: 'Rhein-Lahn-Kreis',
  EN: 'Ennepe-Ruhr-Kreis',
  ER: 'Stadt Erlangen',
  ERB: 'Odenwaldkreis',
  ERH: 'Landkreis Erlangen-Höchstadt',
  ERK: 'Kreis Heinsberg',
  ERZ: 'Erzgebirgskreis',
  ES: 'Landkreis Esslingen',
  ESB: 'Landkreis Amberg-Sulzbach; Landkreis Bayreuth; Landkreis Neustadt an der Waldnaab; Landkreis Nürnberger Land',
  ESW: 'Werra-Meißner-Kreis',
  EU: 'Kreis Euskirchen',
  EW: 'Landkreis Barnim',
  F: 'Stadt Frankfurt am Main',
  FB: 'Wetteraukreis',
  FD: 'Landkreis Fulda',
  FDB: 'Landkreis Aichach-Friedberg',
  FDS: 'Landkreis Freudenstadt',
  FEU: 'Landkreis Ansbach',
  FF: 'Stadt Frankfurt (Oder)',
  FFB: 'Landkreis Fürstenfeldbruck',
  FG: 'Landkreis Mittelsachsen',
  FI: 'Landkreis Elbe-Elster',
  FKB: 'Landkreis Waldeck-Frankenberg',
  FL: 'Stadt Flensburg',
  'FLÖ': 'Landkreis Mittelsachsen',
  FN: 'Bodenseekreis',
  FO: 'Landkreis Forchheim',
  FOR: 'Landkreis Spree-Neiße',
  FR: 'Stadt Freiburg im Breisgau; Landkreis Breisgau-Hochschwarzwald',
  FRG: 'Landkreis Freyung-Grafenau',
  FRI: 'Landkreis Friesland',
  FRW: 'Landkreis Märkisch-Oderland',
  FS: 'Landkreis Freising',
  FT: 'Stadt Frankenthal (Pfalz)',
  FTL: 'Landkreis Sächsische Schweiz-Osterzgebirge',
  FW: 'Landkreis Oder-Spree',
  FZ: 'Schwalm-Eder-Kreis',
  'FÜ': 'Stadt und Landkreis Fürth',
  'FÜS': 'Landkreis Ostallgäu',
  G: 'Stadt Gera',
  GA: 'Altmarkkreis Salzwedel',
  GAN: 'Landkreis Northeim',
  GAP: 'Landkreis Garmisch-Partenkirchen',
  GC: 'Landkreis Zwickau',
  GD: 'Ostalbkreis',
  GDB: 'Landkreis Nordwestmecklenburg',
  GE: 'Stadt Gelsenkirchen',
  GEL: 'Kreis Kleve',
  GEO: 'Landkreis Haßberge; Landkreis Schweinfurt',
  GER: 'Landkreis Germersheim',
  GF: 'Landkreis Gifhorn',
  GG: 'Kreis Groß-Gerau',
  GHA: 'Landkreis Leipzig',
  GHC: 'Landkreis Wittenberg',
  GI: 'Landkreis Gießen',
  GK: 'Kreis Heinsberg',
  GL: 'Rheinisch-Bergischer Kreis',
  GLA: 'Kreis Recklinghausen',
  GM: 'Oberbergischer Kreis',
  GMN: 'Landkreis Vorpommern-Rügen',
  GN: 'Main-Kinzig-Kreis',
  GNT: 'Landkreis Jerichower Land',
  GOA: 'Rhein-Hunsrück-Kreis',
  GOH: 'Rhein-Lahn-Kreis',
  GP: 'Landkreis Göppingen',
  GR: 'Landkreis Görlitz',
  GRA: 'Landkreis Freyung-Grafenau',
  GRH: 'Landkreis Meißen',
  GRI: 'Landkreis Rottal-Inn',
  GRM: 'Landkreis Leipzig',
  GRZ: 'Landkreis Greiz',
  GS: 'Landkreis Goslar',
  GT: 'Kreis Gütersloh',
  GTH: 'Landkreis Gotha',
  GUB: 'Landkreis Spree-Neiße',
  GUN: 'Landkreis Weißenburg-Gunzenhausen',
  GV: 'Rhein-Kreis Neuss',
  GVM: 'Landkreis Nordwestmecklenburg',
  GW: 'Landkreis Vorpommern-Greifswald',
  GZ: 'Landkreis Günzburg',
  'GÖ': 'Landkreis Göttingen',
  'GÜ': 'Landkreis Rostock',
  H: 'Region Hannover',
  HA: 'Stadt Hagen',
  HAB: 'Landkreis Bad Kissingen',
  HAL: 'Stadt Halle (Saale)',
  HAM: 'Stadt Hamm',
  HAS: 'Landkreis Haßberge',
  HB: 'Stadt Bremen; Stadt Bremerhaven',
  HBN: 'Landkreis Hildburghausen',
  HBS: 'Landkreis Harz',
  HC: 'Landkreis Mittelsachsen',
  HCH: 'Landkreis Freudenstadt; Zollernalbkreis',
  HD: 'Stadt Heidelberg; Rhein-Neckar-Kreis',
  HDH: 'Landkreis Heidenheim',
  HDL: 'Landkreis Börde',
  HE: 'Landkreis Helmstedt',
  HEB: 'Landkreis Nürnberger Land',
  HEF: 'Landkreis Hersfeld-Rotenburg',
  HEI: 'Kreis Dithmarschen',
  HER: 'Stadt Herne',
  HET: 'Landkreis Mansfeld-Südharz',
  HF: 'Kreis Herford',
  HG: 'Hochtaunuskreis',
  HGN: 'Landkreis Ludwigslust-Parchim',
  HGW: 'Stadt Greifswald',
  HH: 'Freie und Hansestadt Hamburg',
  HHM: 'Burgenlandkreis',
  HI: 'Landkreis Hildesheim',
  HIG: 'Landkreis Eichsfeld',
  HIP: 'Landkreis Roth',
  HK: 'Landkreis Heidekreis',
  HL: 'Stadt Lübeck',
  HM: 'Landkreis Hameln-Pyrmont',
  'HMÜ': 'Landkreis Göttingen',
  HN: 'Stadt und Landkreis Heilbronn',
  HO: 'Stadt und Landkreis Hof',
  HOG: 'Landkreis Kassel',
  HOH: 'Landkreis Haßberge',
  HOL: 'Landkreis Holzminden',
  HOM: 'Saarpfalz-Kreis',
  HOR: 'Landkreis Freudenstadt',
  HOT: 'Landkreis Zwickau',
  HP: 'Landkreis Bergstraße',
  HR: 'Schwalm-Eder-Kreis',
  HRO: 'Stadt Rostock',
  HS: 'Kreis Heinsberg',
  HSK: 'Hochsauerlandkreis',
  HST: 'Stadt Stralsund',
  HU: 'Stadt Hanau; Main-Kinzig-Kreis',
  HV: 'Landkreis Stendal',
  HVL: 'Landkreis Havelland',
  HWI: 'Stadt Wismar',
  HX: 'Kreis Höxter',
  HY: 'Landkreis Bautzen',
  HZ: 'Landkreis Harz',
  'HÖS': 'Landkreis Erlangen-Höchstadt',
  IGB: 'Stadt St. Ingbert',
  IK: 'Ilm-Kreis',
  IL: 'Ilm-Kreis',
  ILL: 'Landkreis Neu-Ulm',
  IN: 'Stadt Ingolstadt',
  IZ: 'Kreis Steinburg',
  J: 'Stadt Jena',
  JB: 'Landkreis Teltow-Fläming',
  JE: 'Landkreis Wittenberg',
  JL: 'Landkreis Jerichower Land',
  'JÜL': 'Kreis Düren',
  K: 'Stadt Köln',
  KA: 'Stadt und Landkreis Karlsruhe',
  KB: 'Landkreis Waldeck-Frankenberg',
  KC: 'Landkreis Kronach',
  KE: 'Stadt Kempten (Allgäu)',
  KEH: 'Landkreis Kelheim',
  KEL: 'Ortenaukreis',
  KEM: 'Landkreis Bayreuth; Landkreis Tirschenreuth',
  KF: 'Stadt Kaufbeuren',
  KG: 'Landkreis Bad Kissingen',
  KH: 'Landkreis Bad Kreuznach',
  KI: 'Stadt Kiel',
  KIB: 'Donnersbergkreis',
  KK: 'Kreis Viersen',
  KL: 'Stadt und Landkreis Kaiserslautern',
  KLE: 'Kreis Kleve',
  KLZ: 'Altmarkkreis Salzwedel',
  KM: 'Landkreis Bautzen',
  KN: 'Landkreis Konstanz',
  KO: 'Stadt Koblenz',
  KR: 'Stadt Krefeld',
  KRU: 'Landkreis Günzburg',
  KS: 'Stadt und Landkreis Kassel',
  KT: 'Landkreis Kitzingen',
  KU: 'Landkreis Kulmbach',
  KUS: 'Landkreis Kusel',
  KW: 'Landkreis Dahme-Spreewald',
  KY: 'Landkreis Ostprignitz-Ruppin',
  KYF: 'Kyffhäuserkreis',
  'KÖN': 'Landkreis Rhön-Grabfeld',
  'KÖT': 'Landkreis Anhalt-Bitterfeld',
  'KÖZ': 'Landkreis Cham',
  'KÜN': 'Hohenlohekreis',
  L: 'Stadt und Landkreis Leipzig',
  LA: 'Stadt und Landkreis Landshut',
  LAN: 'Landkreis Dingolfing-Landau',
  LAU: 'Landkreis Nürnberger Land',
  LB: 'Landkreis Ludwigsburg',
  LBS: 'Saale-Orla-Kreis',
  LBZ: 'Landkreis Ludwigslust-Parchim',
  LC: 'Landkreis Dahme-Spreewald',
  LD: 'Stadt Landau in der Pfalz',
  LDK: 'Lahn-Dill-Kreis',
  LDS: 'Landkreis Dahme-Spreewald',
  LE: 'Kreis Lippe',
  LEO: 'Landkreis Böblingen',
  LER: 'Landkreis Leer',
  LEV: 'Stadt Leverkusen',
  LF: 'Landkreis Altötting; Landkreis Berchtesgadener Land; Landkreis Traunstein',
  LG: 'Landkreis Lüneburg',
  LH: 'Kreis Coesfeld; Kreis Unna',
  LI: 'Landkreis Lindau (Bodensee)',
  LIB: 'Landkreis Elbe-Elster',
  LIF: 'Landkreis Lichtenfels',
  LIP: 'Kreis Lippe',
  LK: 'Kreis Minden-Lübbecke',
  LL: 'Landkreis Landsberg am Lech',
  LM: 'Landkreis Limburg-Weilburg',
  LN: 'Landkreis Dahme-Spreewald',
  LOS: 'Landkreis Oder-Spree',
  LP: 'Kreis Soest',
  LR: 'Ortenaukreis',
  LRO: 'Landkreis Rostock',
  LSZ: 'Unstrut-Hainich-Kreis',
  LU: 'Stadt Ludwigshafen am Rhein',
  LUK: 'Landkreis Teltow-Fläming',
  LUP: 'Landkreis Ludwigslust-Parchim',
  LWL: 'Landkreis Ludwigslust-Parchim',
  'LÖ': 'Landkreis Lörrach',
  'LÖB': 'Landkreis Görlitz',
  'LÜN': 'Kreis Unna',
  M: 'Stadt und Landkreis München',
  MA: 'Stadt Mannheim',
  MAB: 'Erzgebirgskreis',
  MAI: 'Landkreis Kelheim; Landkreis Landshut',
  MAK: 'Landkreis Wunsiedel im Fichtelgebirge',
  MAL: 'Landkreis Landshut; Landkreis Straubing-Bogen',
  MB: 'Landkreis Miesbach',
  MC: 'Landkreis Mecklenburgische Seenplatte',
  MD: 'Stadt Magdeburg',
  ME: 'Kreis Mettmann',
  MED: 'Kreis Dithmarschen',
  MEG: 'Schwalm-Eder-Kreis',
  MEI: 'Landkreis Meißen',
  MEK: 'Erzgebirgskreis',
  MEL: 'Landkreis Osnabrück',
  MER: 'Saalekreis',
  MET: 'Landkreis Rhön-Grabfeld',
  MG: 'Stadt Mönchengladbach',
  MGH: 'Main-Tauber-Kreis',
  MGN: 'Landkreis Schmalkalden-Meiningen',
  MH: 'Stadt Mülheim an der Ruhr',
  MHL: 'Unstrut-Hainich-Kreis',
  MI: 'Kreis Minden-Lübbecke',
  MIL: 'Landkreis Miltenberg',
  MK: 'Märkischer Kreis',
  MKK: 'Main-Kinzig-Kreis',
  ML: 'Landkreis Mansfeld-Südharz',
  MM: 'Stadt Memmingen',
  MN: 'Landkreis Unterallgäu',
  MO: 'Kreis Wesel',
  MOD: 'Landkreis Ostallgäu',
  MOL: 'Landkreis Märkisch-Oderland',
  MON: 'Städteregion Aachen; Kreis Düren',
  MOS: 'Neckar-Odenwald-Kreis',
  MQ: 'Saalekreis',
  MR: 'Landkreis Marburg-Biedenkopf',
  MS: 'Stadt Münster',
  MSE: 'Landkreis Mecklenburgische Seenplatte',
  MSH: 'Landkreis Mansfeld-Südharz',
  MSP: 'Landkreis Main-Spessart',
  MST: 'Landkreis Mecklenburgische Seenplatte',
  MTK: 'Main-Taunus-Kreis',
  MTL: 'Landkreis Leipzig',
  MU: 'Landkreis München',
  MUC: 'Stadt München',
  MW: 'Landkreis Mittelsachsen',
  MY: 'Landkreis Mayen-Koblenz',
  MYK: 'Landkreis Mayen-Koblenz',
  MZ: 'Stadt Mainz; Landkreis Mainz-Bingen',
  MZG: 'Landkreis Merzig-Wadern',
  'MÜ': 'Landkreis Mühldorf am Inn',
  'MÜB': 'Landkreis Bayreuth; Landkreis Hof',
  'MÜL': 'Landkreis Breisgau-Hochschwarzwald',
  'MÜR': 'Landkreis Mecklenburgische Seenplatte',
  N: 'Stadt Nürnberg; Landkreis Nürnberger Land',
  NAB: 'Landkreis Amberg-Sulzbach; Landkreis Schwandorf',
  NAI: 'Landkreis Hof',
  NAU: 'Landkreis Havelland',
  NB: 'Stadt Neubrandenburg',
  ND: 'Landkreis Neuburg-Schrobenhausen',
  NDH: 'Landkreis Nordhausen',
  NE: 'Rhein-Kreis Neuss',
  NEA: 'Landkreis Neustadt an der Aisch-Bad Windsheim',
  NEB: 'Burgenlandkreis',
  NEC: 'Stadt und Landkreis Coburg',
  NEN: 'Landkreis Schwandorf',
  NES: 'Landkreis Rhön-Grabfeld',
  NEU: 'Landkreis Breisgau-Hochschwarzwald',
  NEW: 'Landkreis Neustadt an der Waldnaab',
  NF: 'Kreis Nordfriesland',
  NH: 'Landkreis Sonneberg',
  NI: 'Landkreis Nienburg/Weser',
  NK: 'Landkreis Neunkirchen',
  NM: 'Landkreis Neumarkt in der Oberpfalz',
  NMB: 'Burgenlandkreis',
  NMS: 'Stadt Neumünster',
  NOH: 'Landkreis Grafschaft Bentheim',
  NOL: 'Landkreis Görlitz',
  NOM: 'Landkreis Northeim',
  NOR: 'Landkreis Aurich',
  NP: 'Landkreis Ostprignitz-Ruppin',
  NR: 'Landkreis Neuwied',
  NT: 'Landkreis Esslingen',
  NU: 'Landkreis Neu-Ulm',
  NVP: 'Landkreis Vorpommern-Rügen',
  NW: 'Stadt Neustadt an der Weinstraße',
  NWM: 'Landkreis Nordwestmecklenburg',
  NY: 'Landkreis Görlitz',
  NZ: 'Landkreis Mecklenburgische Seenplatte',
  'NÖ': 'Landkreis Donau-Ries',
  OA: 'Landkreis Oberallgäu',
  OAL: 'Landkreis Ostallgäu',
  OB: 'Stadt Oberhausen',
  OBB: 'Landkreis Miltenberg',
  OBG: 'Landkreis Stendal',
  OC: 'Landkreis Börde',
  OCH: 'Landkreis Würzburg',
  OD: 'Kreis Stormarn',
  OE: 'Kreis Olpe',
  OF: 'Stadt Offenbach am Main; Landkreis Offenbach',
  OG: 'Ortenaukreis',
  OH: 'Kreis Ostholstein',
  OHA: 'Landkreis Göttingen',
  OHV: 'Landkreis Oberhavel',
  OHZ: 'Landkreis Osterholz',
  OK: 'Landkreis Börde',
  OL: 'Stadt und Landkreis Oldenburg',
  OP: 'Stadt Leverkusen',
  OPR: 'Landkreis Ostprignitz-Ruppin',
  OS: 'Stadt und Landkreis Osnabrück',
  OSL: 'Landkreis Oberspreewald-Lausitz',
  OTW: 'Landkreis Neunkirchen',
  OVI: 'Landkreis Schwandorf',
  OVL: 'Vogtlandkreis',
  OVP: 'Landkreis Vorpommern-Greifswald',
  OZ: 'Landkreis Nordsachsen',
  P: 'Stadt Potsdam',
  PA: 'Stadt und Landkreis Passau',
  PAF: 'Landkreis Pfaffenhofen an der Ilm',
  PAN: 'Landkreis Rottal-Inn',
  PAR: 'Landkreis Kelheim; Landkreis Neumarkt in der Oberpfalz',
  PB: 'Kreis Paderborn',
  PCH: 'Landkreis Ludwigslust-Parchim',
  PE: 'Landkreis Peine',
  PEG: 'Landkreis Bayreuth; Landkreis Forchheim; Landkreis Nürnberger Land',
  PF: 'Stadt Pforzheim; Enzkreis',
  PI: 'Kreis Pinneberg',
  PIR: 'Landkreis Sächsische Schweiz-Osterzgebirge',
  PL: 'Vogtlandkreis',
  'PLÖ': 'Kreis Plön',
  PM: 'Landkreis Potsdam-Mittelmark',
  PN: 'Saale-Orla-Kreis',
  PR: 'Landkreis Prignitz',
  'PRÜ': 'Eifelkreis Bitburg-Prüm',
  PS: 'Stadt Pirmasens; Landkreis Südwestpfalz',
  PW: 'Landkreis Vorpommern-Greifswald',
  PZ: 'Landkreis Uckermark',
  QFT: 'Saalekreis',
  QLB: 'Landkreis Harz',
  R: 'Stadt und Landkreis Regensburg',
  RA: 'Landkreis Rastatt',
  RC: 'Vogtlandkreis',
  RD: 'Kreis Rendsburg-Eckernförde',
  RDG: 'Landkreis Vorpommern-Rügen',
  RE: 'Kreis Recklinghausen',
  REG: 'Landkreis Regen',
  REH: 'Landkreis Hof; Landkreis Wunsiedel im Fichtelgebirge',
  REI: 'Landkreis Berchtesgadener Land',
  RG: 'Landkreis Meißen',
  RH: 'Landkreis Roth',
  RI: 'Landkreis Schaumburg',
  RID: 'Landkreis Kelheim',
  RIE: 'Landkreis Meißen',
  RL: 'Landkreis Mittelsachsen',
  RM: 'Landkreis Mecklenburgische Seenplatte',
  RN: 'Landkreis Havelland',
  RO: 'Stadt und Landkreis Rosenheim',
  ROD: 'Landkreis Cham; Landkreis Schwandorf',
  ROF: 'Landkreis Hersfeld-Rotenburg',
  ROK: 'Donnersbergkreis',
  ROL: 'Landkreis Kelheim; Landkreis Landshut',
  ROS: 'Landkreis Rostock',
  ROT: 'Landkreis Ansbach',
  ROW: 'Landkreis Rotenburg (Wümme)',
  RP: 'Rhein-Pfalz-Kreis',
  RS: 'Stadt Remscheid',
  RSL: 'Stadt Dessau-Roßlau',
  RT: 'Landkreis Reutlingen',
  RU: 'Landkreis Saalfeld-Rudolstadt',
  RV: 'Landkreis Ravensburg',
  RW: 'Landkreis Rottweil',
  RZ: 'Kreis Herzogtum Lauenburg',
  'RÜD': 'Rheingau-Taunus-Kreis',
  'RÜG': 'Landkreis Vorpommern-Rügen',
  S: 'Stadt Stuttgart',
  SAB: 'Landkreis Trier-Saarburg',
  SAD: 'Landkreis Schwandorf',
  SAN: 'Landkreis Hof; Landkreis Kronach; Landkreis Kulmbach',
  SAW: 'Altmarkkreis Salzwedel',
  SB: 'Regionalverband Saarbrücken',
  SBG: 'Landkreis Vorpommern-Greifswald',
  SBK: 'Salzlandkreis',
  SC: 'Stadt Schwabach',
  SCZ: 'Saale-Orla-Kreis',
  SDH: 'Kyffhäuserkreis',
  SDL: 'Landkreis Stendal',
  SDT: 'Landkreis Uckermark',
  SE: 'Kreis Segeberg',
  SEB: 'Landkreis Sächsische Schweiz-Osterzgebirge',
  SEE: 'Landkreis Märkisch-Oderland',
  SEF: 'Landkreis Neustadt an der Aisch-Bad Windsheim',
  SEL: 'Landkreis Wunsiedel im Fichtelgebirge',
  SFB: 'Landkreis Oberspreewald-Lausitz',
  SFT: 'Salzlandkreis',
  SG: 'Stadt Solingen',
  SGH: 'Landkreis Mansfeld-Südharz',
  SHA: 'Landkreis Schwäbisch Hall',
  SHG: 'Landkreis Schaumburg',
  SHK: 'Saale-Holzland-Kreis',
  SHL: 'Stadt Suhl',
  SI: 'Kreis Siegen-Wittgenstein',
  SIG: 'Landkreis Sigmaringen',
  SIM: 'Rhein-Hunsrück-Kreis',
  SK: 'Saalekreis',
  SL: 'Kreis Schleswig-Flensburg',
  SLE: 'Kreis Düren; Kreis Euskirchen',
  SLF: 'Landkreis Saalfeld-Rudolstadt',
  SLG: 'Landkreis Ravensburg; Landkreis Sigmaringen',
  SLK: 'Salzlandkreis',
  SLN: 'Landkreis Altenburger Land',
  SLS: 'Landkreis Saarlouis',
  SLZ: 'Wartburgkreis',
  'SLÜ': 'Main-Kinzig-Kreis',
  SM: 'Landkreis Schmalkalden-Meiningen',
  'SMÜ': 'Landkreis Augsburg',
  SN: 'Stadt Schwerin',
  SNH: 'Rhein-Neckar-Kreis',
  SO: 'Kreis Soest',
  SOB: 'Landkreis Neuburg-Schrobenhausen',
  SOG: 'Landkreis Weilheim-Schongau',
  SOK: 'Saale-Orla-Kreis',
  SON: 'Landkreis Sonneberg',
  SP: 'Stadt Speyer',
  SPB: 'Landkreis Spree-Neiße',
  SPN: 'Landkreis Spree-Neiße',
  SR: 'Stadt Straubing; Landkreis Straubing-Bogen',
  SRB: 'Landkreis Märkisch-Oderland',
  SRO: 'Saale-Holzland-Kreis',
  ST: 'Kreis Steinfurt',
  STA: 'Landkreis Starnberg',
  STB: 'Landkreis Ludwigslust-Parchim',
  STD: 'Landkreis Stade',
  STE: 'Landkreis Lichtenfels',
  STL: 'Erzgebirgskreis',
  STO: 'Landkreis Konstanz',
  SU: 'Rhein-Sieg-Kreis',
  SUL: 'Landkreis Amberg-Sulzbach',
  SW: 'Stadt und Landkreis Schweinfurt',
  SWA: 'Rheingau-Taunus-Kreis',
  SY: 'Landkreis Diepholz',
  SZ: 'Stadt Salzgitter',
  SZB: 'Erzgebirgskreis',
  'SÄK': 'Landkreis Waldshut',
  'SÖM': 'Landkreis Sömmerda',
  'SÜW': 'Landkreis Südliche Weinstraße',
  TBB: 'Main-Tauber-Kreis',
  TDO: 'Landkreis Nordsachsen',
  TE: 'Kreis Steinfurt',
  TET: 'Landkreis Rostock',
  TF: 'Landkreis Teltow-Fläming',
  TG: 'Landkreis Nordsachsen',
  TIR: 'Landkreis Tirschenreuth',
  TO: 'Landkreis Nordsachsen',
  TP: 'Landkreis Uckermark',
  TR: 'Stadt Trier; Landkreis Trier-Saarburg',
  TS: 'Landkreis Traunstein',
  TT: 'Bodenseekreis',
  TUT: 'Landkreis Tuttlingen',
  'TÖL': 'Landkreis Bad Tölz-Wolfratshausen',
  'TÜ': 'Landkreis Tübingen',
  UE: 'Landkreis Uelzen',
  UEM: 'Landkreis Vorpommern-Greifswald',
  UFF: 'Landkreis Neustadt an der Aisch-Bad Windsheim',
  UH: 'Unstrut-Hainich-Kreis',
  UL: 'Stadt Ulm; Alb-Donau-Kreis',
  UM: 'Landkreis Uckermark',
  UN: 'Kreis Unna',
  USI: 'Hochtaunuskreis',
  V: 'Vogtlandkreis',
  VAI: 'Landkreis Ludwigsburg',
  VB: 'Vogelsbergkreis',
  VEC: 'Landkreis Vechta',
  VER: 'Landkreis Verden',
  VG: 'Landkreis Vorpommern-Greifswald',
  VIB: 'Landkreis Landshut; Landkreis Mühldorf am Inn; Landkreis Rottal-Inn',
  VIE: 'Kreis Viersen',
  VIT: 'Landkreis Regen',
  VK: 'Stadt Völklingen',
  VOH: 'Landkreis Neustadt an der Waldnaab',
  VR: 'Landkreis Vorpommern-Rügen',
  VS: 'Schwarzwald-Baar-Kreis',
  W: 'Stadt Wuppertal',
  WA: 'Landkreis Waldeck-Frankenberg',
  WAF: 'Kreis Warendorf',
  WAK: 'Wartburgkreis',
  WAN: 'Stadt Herne',
  WAR: 'Kreis Höxter',
  WAT: 'Stadt Bochum',
  WB: 'Landkreis Wittenberg',
  WBS: 'Landkreis Eichsfeld',
  WDA: 'Landkreis Zwickau',
  WE: 'Stadt Weimar',
  WEL: 'Landkreis Limburg-Weilburg',
  WEN: 'Stadt Weiden in der Oberpfalz',
  WER: 'Landkreis Augsburg; Landkreis Dillingen an der Donau',
  WES: 'Kreis Wesel',
  WF: 'Landkreis Wolfenbüttel',
  WG: 'Landkreis Ravensburg',
  WHV: 'Stadt Wilhelmshaven',
  WI: 'Stadt Wiesbaden',
  WIL: 'Landkreis Bernkastel-Wittlich',
  WIS: 'Landkreis Nordwestmecklenburg',
  WIT: 'Ennepe-Ruhr-Kreis',
  WIZ: 'Werra-Meißner-Kreis',
  WK: 'Landkreis Ostprignitz-Ruppin',
  WL: 'Landkreis Harburg',
  WLG: 'Landkreis Vorpommern-Greifswald',
  WM: 'Landkreis Weilheim-Schongau',
  WMS: 'Landkreis Börde',
  WN: 'Rems-Murr-Kreis',
  WND: 'Landkreis St. Wendel',
  WO: 'Stadt Worms',
  WOB: 'Stadt Wolfsburg',
  WOH: 'Landkreis Kassel',
  WOL: 'Landkreis Freudenstadt; Ortenaukreis',
  WOR: 'Landkreis Bad Tölz-Wolfratshausen; Landkreis München; Landkreis Starnberg',
  WOS: 'Landkreis Freyung-Grafenau',
  WR: 'Landkreis Harz',
  WRN: 'Landkreis Mecklenburgische Seenplatte',
  WS: 'Landkreis Mühldorf am Inn; Landkreis Rosenheim',
  WSF: 'Burgenlandkreis',
  WST: 'Landkreis Ammerland',
  WSW: 'Landkreis Görlitz',
  WT: 'Landkreis Waldshut',
  WTL: 'Landkreis Osnabrück',
  WTM: 'Landkreis Wittmund',
  WUG: 'Landkreis Weißenburg-Gunzenhausen',
  WUN: 'Landkreis Wunsiedel im Fichtelgebirge',
  WUR: 'Landkreis Leipzig',
  WW: 'Westerwaldkreis',
  WZ: 'Lahn-Dill-Kreis',
  WZL: 'Landkreis Börde',
  'WÜ': 'Stadt und Landkreis Würzburg',
  'WÜM': 'Landkreis Cham',
  Z: 'Landkreis Zwickau',
  ZE: 'Landkreis Anhalt-Bitterfeld',
  ZEL: 'Landkreis Cochem-Zell',
  ZI: 'Landkreis Görlitz',
  ZIG: 'Schwalm-Eder-Kreis',
  ZP: 'Erzgebirgskreis',
  ZR: 'Landkreis Greiz',
  ZS: 'Landkreis Teltow-Fläming',
  ZW: 'Stadt Zweibrücken; Landkreis Südwestpfalz',
  ZZ: 'Burgenlandkreis',
  'ÖHR': 'Hohenlohekreis',
  'ÜB': 'Bodenseekreis; Landkreis Ravensburg; Landkreis Sigmaringen',
};
