// Herkunft und Bundesland je Unterscheidungszeichen (für die Ortsseiten unter /kennzeichen).
// Quelle: Liste der Kfz-Kennzeichen in Deutschland (Wikipedia, abgerufen Oktober 2026), automatisch aufbereitet.
// o = abgeleitet von (Stadt/Kreis/Region des Kürzels), s = Bundesland/-länder.

export const DISTRICT_INFO: Readonly<Record<string, { o: string; s: readonly string[] }>> = {
  A: { o: 'Augsburg', s: ['Bayern'] },
  AA: { o: 'Aalen', s: ['Baden-Württemberg'] },
  AB: { o: 'Aschaffenburg', s: ['Bayern'] },
  ABG: { o: 'Altenburg', s: ['Thüringen'] },
  ABI: { o: 'Anhalt-Bitterfeld', s: ['Sachsen-Anhalt'] },
  AC: { o: 'Aachen / Aix la Chapelle', s: ['Nordrhein-Westfalen'] },
  AE: { o: 'Auerbach/Vogtl.', s: ['Sachsen'] },
  AH: { o: 'Ahaus', s: ['Nordrhein-Westfalen'] },
  AIB: { o: 'Bad Aibling', s: ['Bayern'] },
  AIC: { o: 'Aichach', s: ['Bayern'] },
  AK: { o: 'Altenkirchen', s: ['Rheinland-Pfalz'] },
  ALF: { o: 'Alfeld', s: ['Niedersachsen'] },
  ALZ: { o: 'Alzenau', s: ['Bayern'] },
  AM: { o: 'Amberg', s: ['Bayern'] },
  AN: { o: 'Ansbach', s: ['Bayern'] },
  ANA: { o: 'Annaberg-Buchholz', s: ['Sachsen'] },
  ANG: { o: 'Angermünde', s: ['Brandenburg'] },
  ANK: { o: 'Anklam', s: ['Mecklenburg-Vorpommern'] },
  'AÖ': { o: 'Altötting', s: ['Bayern'] },
  AP: { o: 'Apolda', s: ['Thüringen'] },
  APD: { o: 'Apolda', s: ['Thüringen'] },
  ARN: { o: 'Arnstadt', s: ['Thüringen'] },
  ART: { o: 'Artern', s: ['Thüringen'] },
  AS: { o: 'Amberg, Sulzbach-Rosenberg', s: ['Bayern'] },
  ASL: { o: 'Aschersleben', s: ['Sachsen-Anhalt'] },
  ASZ: { o: 'Aue, Schwarzenberg/Erzgeb.', s: ['Sachsen'] },
  AT: { o: 'Altentreptow', s: ['Mecklenburg-Vorpommern'] },
  AU: { o: 'Aue', s: ['Sachsen'] },
  AUR: { o: 'Aurich', s: ['Niedersachsen'] },
  AW: { o: 'Ahrweiler', s: ['Rheinland-Pfalz'] },
  AZ: { o: 'Alzey', s: ['Rheinland-Pfalz'] },
  AZE: { o: 'Anhalt-Zerbst/Anhalt', s: ['Sachsen-Anhalt'] },
  B: { o: 'Berlin', s: ['Berlin'] },
  BA: { o: 'Bamberg', s: ['Bayern'] },
  BAD: { o: 'Baden-Baden', s: ['Baden-Württemberg'] },
  BAR: { o: 'Barnim', s: ['Brandenburg'] },
  BB: { o: 'Böblingen', s: ['Baden-Württemberg'] },
  BBG: { o: 'Bernburg', s: ['Sachsen-Anhalt'] },
  BC: { o: 'Biberach an der Riß', s: ['Baden-Württemberg'] },
  BCH: { o: 'Buchen', s: ['Baden-Württemberg'] },
  BE: { o: 'Beckum', s: ['Nordrhein-Westfalen'] },
  BED: { o: 'Brand-Erbisdorf', s: ['Sachsen'] },
  BEL: { o: 'Bad Belzig', s: ['Brandenburg'] },
  BER: { o: 'Bernau bei Berlin', s: ['Brandenburg'] },
  BF: { o: 'Steinfurt#Burgsteinfurt', s: ['Nordrhein-Westfalen'] },
  BGD: { o: 'Berchtesgaden', s: ['Bayern'] },
  BGL: { o: 'Berchtesgadener Land', s: ['Bayern'] },
  BH: { o: 'Bühl', s: ['Baden-Württemberg'] },
  BI: { o: 'Bielefeld', s: ['Nordrhein-Westfalen'] },
  BID: { o: 'Biedenkopf', s: ['Hessen'] },
  BIN: { o: 'Bingen am Rhein', s: ['Rheinland-Pfalz'] },
  BIR: { o: 'Birkenfeld', s: ['Rheinland-Pfalz'] },
  BIT: { o: 'Bitburg', s: ['Rheinland-Pfalz'] },
  BIW: { o: 'Bischofswerda', s: ['Sachsen'] },
  BK: { o: 'Backnang', s: ['Baden-Württemberg', 'Sachsen-Anhalt'] },
  BKS: { o: 'Bernkastel-Kues', s: ['Rheinland-Pfalz'] },
  BL: { o: 'Balingen', s: ['Baden-Württemberg'] },
  BLB: { o: 'Bad Berleburg', s: ['Nordrhein-Westfalen'] },
  BLK: { o: 'Burgenlandkreis', s: ['Sachsen-Anhalt'] },
  BM: { o: 'Bergheim', s: ['Nordrhein-Westfalen'] },
  BN: { o: 'Bonn', s: ['Nordrhein-Westfalen'] },
  BNA: { o: 'Borna', s: ['Sachsen'] },
  BO: { o: 'Bochum', s: ['Nordrhein-Westfalen'] },
  'BÖ': { o: 'Magdeburger Börde', s: ['Sachsen-Anhalt'] },
  BOG: { o: 'Bogen', s: ['Bayern'] },
  BOH: { o: 'Bocholt', s: ['Nordrhein-Westfalen'] },
  BOR: { o: 'Borken', s: ['Nordrhein-Westfalen'] },
  BOT: { o: 'Bottrop', s: ['Nordrhein-Westfalen'] },
  BR: { o: 'Bruchsal', s: ['Baden-Württemberg'] },
  BRA: { o: 'Brake', s: ['Niedersachsen'] },
  BRB: { o: 'Brandenburg', s: ['Brandenburg'] },
  BRG: { o: 'Burg', s: ['Sachsen-Anhalt'] },
  BRK: { o: 'Bad Brückenau', s: ['Bayern'] },
  BRL: { o: 'Braunlage', s: ['Niedersachsen'] },
  BRV: { o: 'Bremervörde', s: ['Niedersachsen'] },
  BS: { o: 'Braunschweig', s: ['Niedersachsen'] },
  BSB: { o: 'Bersenbrück', s: ['Niedersachsen'] },
  BSK: { o: 'Beeskow', s: ['Brandenburg'] },
  BT: { o: 'Bayreuth', s: ['Bayern'] },
  BTF: { o: 'Bitterfeld', s: ['Sachsen-Anhalt'] },
  'BÜD': { o: 'Büdingen', s: ['Hessen'] },
  BUL: { o: 'Burglengenfeld', s: ['Bayern'] },
  'BÜR': { o: 'Büren', s: ['Nordrhein-Westfalen'] },
  'BÜS': { o: 'Büsingen', s: ['Baden-Württemberg'] },
  'BÜZ': { o: 'Bützow', s: ['Mecklenburg-Vorpommern'] },
  BZ: { o: 'Bautzen', s: ['Sachsen'] },
  C: { o: 'Chemnitz', s: ['Sachsen'] },
  CA: { o: 'Calau', s: ['Brandenburg'] },
  CAS: { o: 'Castrop-Rauxel', s: ['Nordrhein-Westfalen'] },
  CB: { o: 'Cottbus', s: ['Brandenburg'] },
  CE: { o: 'Celle', s: ['Niedersachsen'] },
  CHA: { o: 'Cham', s: ['Bayern'] },
  CLP: { o: 'Cloppenburg', s: ['Niedersachsen'] },
  CLZ: { o: 'Clausthal-Zellerfeld', s: ['Niedersachsen'] },
  CO: { o: 'Coburg', s: ['Bayern'] },
  COC: { o: 'Cochem', s: ['Rheinland-Pfalz'] },
  COE: { o: 'Coesfeld', s: ['Nordrhein-Westfalen'] },
  CR: { o: 'Crailsheim', s: ['Baden-Württemberg'] },
  CUX: { o: 'Cuxhaven', s: ['Niedersachsen'] },
  CW: { o: 'Calw', s: ['Baden-Württemberg'] },
  D: { o: 'Düsseldorf', s: ['Nordrhein-Westfalen'] },
  DA: { o: 'Darmstadt', s: ['Hessen'] },
  DAH: { o: 'Dachau', s: ['Bayern'] },
  DAN: { o: 'Dannenberg', s: ['Niedersachsen'] },
  DAU: { o: 'Daun', s: ['Rheinland-Pfalz'] },
  DBR: { o: 'Bad Doberan', s: ['Mecklenburg-Vorpommern'] },
  DD: { o: 'Dresden', s: ['Sachsen'] },
  DE: { o: 'Dessau', s: ['Sachsen-Anhalt'] },
  DEG: { o: 'Deggendorf', s: ['Bayern'] },
  DEL: { o: 'Delmenhorst', s: ['Niedersachsen'] },
  DGF: { o: 'Dingolfing', s: ['Bayern'] },
  DH: { o: 'Diepholz', s: ['Niedersachsen'] },
  DI: { o: 'Dieburg', s: ['Hessen'] },
  DIL: { o: 'Dillenburg', s: ['Hessen'] },
  DIN: { o: 'Dinslaken', s: ['Nordrhein-Westfalen'] },
  DIZ: { o: 'Diez', s: ['Rheinland-Pfalz'] },
  DKB: { o: 'Dinkelsbühl', s: ['Bayern'] },
  DL: { o: 'Döbeln', s: ['Sachsen'] },
  DLG: { o: 'Dillingen an der Donau', s: ['Bayern'] },
  DM: { o: 'Demmin', s: ['Mecklenburg-Vorpommern'] },
  DN: { o: 'Düren', s: ['Nordrhein-Westfalen'] },
  DO: { o: 'Dortmund', s: ['Nordrhein-Westfalen'] },
  DON: { o: 'Donauwörth', s: ['Bayern'] },
  DS: { o: 'Donaueschingen', s: ['Baden-Württemberg'] },
  DT: { o: 'Detmold', s: ['Nordrhein-Westfalen'] },
  DU: { o: 'Duisburg', s: ['Nordrhein-Westfalen'] },
  DUD: { o: 'Duderstadt', s: ['Niedersachsen'] },
  'DÜW': { o: 'Bad Dürkheim an der Deutsche Weinstraße', s: ['Rheinland-Pfalz'] },
  DW: { o: 'Dippoldiswalde', s: ['Sachsen'] },
  DZ: { o: 'Delitzsch', s: ['Sachsen'] },
  E: { o: 'Essen', s: ['Nordrhein-Westfalen'] },
  EA: { o: 'Eisenach', s: ['Thüringen'] },
  EB: { o: 'Eilenburg', s: ['Sachsen'] },
  EBE: { o: 'Ebersberg', s: ['Bayern'] },
  EBN: { o: 'Ebern', s: ['Bayern'] },
  EBS: { o: 'Ebermannstadt', s: ['Bayern'] },
  ECK: { o: 'Eckernförde', s: ['Schleswig-Holstein'] },
  ED: { o: 'Erding', s: ['Bayern'] },
  EE: { o: 'Elbe, Schwarze Elster', s: ['Brandenburg'] },
  EF: { o: 'Erfurt', s: ['Thüringen'] },
  EG: { o: 'Eggenfelden', s: ['Bayern'] },
  EH: { o: 'Eisenhüttenstadt', s: ['Brandenburg'] },
  EI: { o: 'Eichstätt', s: ['Bayern'] },
  EIC: { o: 'Eichsfeld', s: ['Thüringen'] },
  EIL: { o: 'Lutherstadt Eisleben', s: ['Sachsen-Anhalt'] },
  EIN: { o: 'Einbeck', s: ['Niedersachsen'] },
  EIS: { o: 'Eisenberg', s: ['Thüringen'] },
  EL: { o: 'Emsland', s: ['Niedersachsen'] },
  EM: { o: 'Emmendingen', s: ['Baden-Württemberg'] },
  EMD: { o: 'Emden', s: ['Niedersachsen'] },
  EMS: { o: 'Bad Ems', s: ['Rheinland-Pfalz'] },
  EN: { o: 'Ennepe', s: ['Nordrhein-Westfalen'] },
  ER: { o: 'Erlangen', s: ['Bayern'] },
  ERB: { o: 'Erbach', s: ['Hessen'] },
  ERH: { o: 'Erlangen, Höchstadt', s: ['Bayern'] },
  ERK: { o: 'Erkelenz', s: ['Nordrhein-Westfalen'] },
  ERZ: { o: 'Erzgebirge', s: ['Sachsen'] },
  ES: { o: 'Esslingen am Neckar', s: ['Baden-Württemberg'] },
  ESB: { o: 'Eschenbach in der Oberpfalz', s: ['Bayern'] },
  ESW: { o: 'Eschwege', s: ['Hessen'] },
  EU: { o: 'Euskirchen', s: ['Nordrhein-Westfalen'] },
  EW: { o: 'Eberswalde', s: ['Brandenburg'] },
  F: { o: 'Frankfurt', s: ['Hessen'] },
  FB: { o: 'Friedberg', s: ['Hessen'] },
  FD: { o: 'Fulda', s: ['Hessen'] },
  FDB: { o: 'Friedberg', s: ['Bayern'] },
  FDS: { o: 'Freudenstadt', s: ['Baden-Württemberg'] },
  FEU: { o: 'Feuchtwangen', s: ['Bayern'] },
  FF: { o: 'Frankfurt', s: ['Brandenburg'] },
  FFB: { o: 'Fürstenfeldbruck', s: ['Bayern'] },
  FG: { o: 'Freiberg', s: ['Sachsen'] },
  FI: { o: 'Finsterwalde', s: ['Brandenburg'] },
  FKB: { o: 'Frankenberg', s: ['Hessen'] },
  FL: { o: 'Flensburg', s: ['Schleswig-Holstein'] },
  'FLÖ': { o: 'Flöha', s: ['Sachsen'] },
  FN: { o: 'Friedrichshafen', s: ['Baden-Württemberg'] },
  FO: { o: 'Forchheim', s: ['Bayern'] },
  FOR: { o: 'Forst', s: ['Brandenburg'] },
  FR: { o: 'Freiburg', s: ['Baden-Württemberg'] },
  FRG: { o: 'Freyung, Grafenau', s: ['Bayern'] },
  FRI: { o: 'Frieslande', s: ['Niedersachsen'] },
  FRW: { o: 'Bad Freienwalde', s: ['Brandenburg'] },
  FS: { o: 'Freising', s: ['Bayern'] },
  FT: { o: 'Frankenthal', s: ['Rheinland-Pfalz'] },
  FTL: { o: 'Freital', s: ['Sachsen'] },
  'FÜ': { o: 'Fürth', s: ['Bayern'] },
  'FÜS': { o: 'Füssen', s: ['Bayern'] },
  FW: { o: 'Fürstenwalde/Spree', s: ['Brandenburg'] },
  FZ: { o: 'Fritzlar', s: ['Hessen'] },
  G: { o: 'Gera', s: ['Thüringen'] },
  GA: { o: 'Gardelegen', s: ['Sachsen-Anhalt'] },
  GAN: { o: 'Bad Gandersheim', s: ['Niedersachsen'] },
  GAP: { o: 'Garmisch-Partenkirchen', s: ['Bayern'] },
  GC: { o: 'Glauchau', s: ['Sachsen'] },
  GD: { o: 'Schwäbisch Gmünd', s: ['Baden-Württemberg'] },
  GDB: { o: 'Gadebusch', s: ['Mecklenburg-Vorpommern'] },
  GE: { o: 'Gelsenkirchen', s: ['Nordrhein-Westfalen'] },
  GEL: { o: 'Geldern', s: ['Nordrhein-Westfalen'] },
  GEO: { o: 'Gerolzhofen', s: ['Bayern'] },
  GER: { o: 'Germersheim', s: ['Rheinland-Pfalz'] },
  GF: { o: 'Gifhorn', s: ['Niedersachsen'] },
  GG: { o: 'Groß-Gerau', s: ['Hessen'] },
  GHA: { o: 'Geithain', s: ['Sachsen'] },
  GHC: { o: 'Gräfenhainichen', s: ['Sachsen-Anhalt'] },
  GI: { o: 'Gießen', s: ['Hessen'] },
  GK: { o: 'Geilenkirchen', s: ['Nordrhein-Westfalen'] },
  GL: { o: 'Bergisch Gladbach', s: ['Nordrhein-Westfalen'] },
  GLA: { o: 'Gladbeck', s: ['Nordrhein-Westfalen'] },
  GM: { o: 'Gummersbach', s: ['Nordrhein-Westfalen'] },
  GMN: { o: 'Grimmen', s: ['Mecklenburg-Vorpommern'] },
  GN: { o: 'Gelnhausen', s: ['Hessen'] },
  GNT: { o: 'Genthin', s: ['Sachsen-Anhalt'] },
  'GÖ': { o: 'Göttingen', s: ['Niedersachsen'] },
  GOA: { o: 'Sankt Goar', s: ['Rheinland-Pfalz'] },
  GOH: { o: 'Sankt Goarshausen', s: ['Rheinland-Pfalz'] },
  GP: { o: 'Göppingen', s: ['Baden-Württemberg'] },
  GR: { o: 'Görlitz', s: ['Sachsen'] },
  GRA: { o: 'Grafenau', s: ['Bayern'] },
  GRH: { o: 'Großenhain', s: ['Sachsen'] },
  GRI: { o: 'Bad Griesbach im Rottal', s: ['Bayern'] },
  GRM: { o: 'Grimma', s: ['Sachsen'] },
  GRZ: { o: 'Greiz', s: ['Thüringen'] },
  GS: { o: 'Goslar', s: ['Niedersachsen'] },
  GT: { o: 'Gütersloh', s: ['Nordrhein-Westfalen'] },
  GTH: { o: 'Gotha', s: ['Thüringen'] },
  'GÜ': { o: 'Güstrow', s: ['Mecklenburg-Vorpommern'] },
  GUB: { o: 'Guben', s: ['Brandenburg'] },
  GUN: { o: 'Gunzenhausen', s: ['Bayern'] },
  GV: { o: 'Grevenbroich', s: ['Nordrhein-Westfalen'] },
  GVM: { o: 'Grevesmühlen', s: ['Mecklenburg-Vorpommern'] },
  GW: { o: 'Greifswald', s: ['Mecklenburg-Vorpommern'] },
  GZ: { o: 'Günzburg', s: ['Bayern'] },
  H: { o: 'Hannover', s: ['Niedersachsen'] },
  HA: { o: 'Hagen', s: ['Nordrhein-Westfalen'] },
  HAB: { o: 'Hammelburg', s: ['Bayern'] },
  HAL: { o: 'Halle', s: ['Sachsen-Anhalt'] },
  HAM: { o: 'Hamm', s: ['Nordrhein-Westfalen'] },
  HAS: { o: 'Haßfurt', s: ['Bayern'] },
  HB: { o: 'Hansestadt Bremen', s: ['Bremen'] },
  HBN: { o: 'Hildburghausen', s: ['Thüringen'] },
  HBS: { o: 'Halberstadt', s: ['Sachsen-Anhalt'] },
  HC: { o: 'Hainichen', s: ['Sachsen'] },
  HCH: { o: 'Hechingen', s: ['Baden-Württemberg'] },
  HD: { o: 'Heidelberg', s: ['Baden-Württemberg'] },
  HDH: { o: 'Heidenheim an der Brenz', s: ['Baden-Württemberg'] },
  HDL: { o: 'Haldensleben', s: ['Sachsen-Anhalt'] },
  HE: { o: 'Helmstedt', s: ['Niedersachsen'] },
  HEB: { o: 'Hersbruck', s: ['Bayern'] },
  HEF: { o: 'Bad Hersfeld', s: ['Hessen'] },
  HEI: { o: 'Heide', s: ['Schleswig-Holstein'] },
  HER: { o: 'Herne', s: ['Nordrhein-Westfalen'] },
  HET: { o: 'Hettstedt', s: ['Sachsen-Anhalt'] },
  HF: { o: 'Herford', s: ['Nordrhein-Westfalen'] },
  HG: { o: 'Bad Homburg vor der Höhe', s: ['Hessen'] },
  HGN: { o: 'Hagenow', s: ['Mecklenburg-Vorpommern'] },
  HGW: { o: 'Hansestadt Greifswald', s: ['Mecklenburg-Vorpommern'] },
  HH: { o: 'Hansestadt Hamburg', s: ['Hamburg'] },
  HHM: { o: 'Hohenmölsen', s: ['Sachsen-Anhalt'] },
  HI: { o: 'Hildesheim', s: ['Niedersachsen'] },
  HIG: { o: 'Heilbad Heiligenstadt', s: ['Thüringen'] },
  HIP: { o: 'Hilpoltstein', s: ['Bayern'] },
  HK: { o: 'Lüneburger Heidekreis', s: ['Niedersachsen'] },
  HL: { o: 'Hansestadt Lübeck', s: ['Schleswig-Holstein'] },
  HM: { o: 'Hameln', s: ['Niedersachsen'] },
  'HMÜ': { o: 'Hann. Münden', s: ['Niedersachsen'] },
  HN: { o: 'Heilbronn', s: ['Baden-Württemberg'] },
  HO: { o: 'Hof', s: ['Bayern'] },
  HOG: { o: 'Hofgeismar', s: ['Hessen'] },
  HOH: { o: 'Hofheim in Unterfranken', s: ['Bayern'] },
  HOL: { o: 'Holzminden', s: ['Niedersachsen'] },
  HOM: { o: 'Homburg', s: ['Saarland'] },
  HOR: { o: 'Horb am Neckar', s: ['Baden-Württemberg'] },
  'HÖS': { o: 'Höchstadt an der Aisch', s: ['Bayern'] },
  HOT: { o: 'Hohenstein-Ernstthal', s: ['Sachsen'] },
  HP: { o: 'Heppenheim', s: ['Hessen'] },
  HR: { o: 'Homberg', s: ['Hessen'] },
  HRO: { o: 'Hansestadt Rostock', s: ['Mecklenburg-Vorpommern'] },
  HS: { o: 'Heinsberg', s: ['Nordrhein-Westfalen'] },
  HSK: { o: 'Hochsauerlandkreis', s: ['Nordrhein-Westfalen'] },
  HST: { o: 'Hansestadt Stralsund', s: ['Mecklenburg-Vorpommern'] },
  HU: { o: 'Hanau', s: ['Hessen'] },
  HV: { o: 'Havelberg', s: ['Sachsen-Anhalt'] },
  HVL: { o: 'Havelland', s: ['Brandenburg'] },
  HWI: { o: 'Hansestadt Wismar', s: ['Mecklenburg-Vorpommern'] },
  HX: { o: 'Höxter', s: ['Nordrhein-Westfalen'] },
  HY: { o: 'Hoyerswerda', s: ['Sachsen'] },
  HZ: { o: 'Harz', s: ['Sachsen-Anhalt'] },
  IGB: { o: 'Ingbert', s: ['Saarland'] },
  IK: { o: 'Ilm-Kreis', s: ['Thüringen'] },
  IL: { o: 'Ilmenau', s: ['Thüringen'] },
  ILL: { o: 'Illertissen', s: ['Bayern'] },
  IN: { o: 'Ingolstadt', s: ['Bayern'] },
  IZ: { o: 'Itzehoe', s: ['Schleswig-Holstein'] },
  J: { o: 'Jena', s: ['Thüringen'] },
  JB: { o: 'Jüterbog', s: ['Brandenburg'] },
  JE: { o: 'Jessen', s: ['Sachsen-Anhalt'] },
  JL: { o: 'Jerichow Land', s: ['Sachsen-Anhalt'] },
  'JÜL': { o: 'Jülich', s: ['Nordrhein-Westfalen'] },
  K: { o: 'Köln', s: ['Nordrhein-Westfalen'] },
  KA: { o: 'Karlsruhe', s: ['Baden-Württemberg'] },
  KB: { o: 'Korbach', s: ['Hessen'] },
  KC: { o: 'Kronach', s: ['Bayern'] },
  KE: { o: 'Kempten', s: ['Bayern'] },
  KEH: { o: 'Kelheim', s: ['Bayern'] },
  KEL: { o: 'Kehl', s: ['Baden-Württemberg'] },
  KEM: { o: 'Kemnath', s: ['Bayern'] },
  KF: { o: 'Kaufbeuren', s: ['Bayern'] },
  KG: { o: 'Bad Kissingen', s: ['Bayern'] },
  KH: { o: 'Bad Kreuznach', s: ['Rheinland-Pfalz'] },
  KI: { o: 'Kiel', s: ['Schleswig-Holstein'] },
  KIB: { o: 'Kirchheimbolanden', s: ['Rheinland-Pfalz'] },
  KK: { o: 'Kempen, Krefeld', s: ['Nordrhein-Westfalen'] },
  KL: { o: 'Kaiserslautern', s: ['Rheinland-Pfalz'] },
  KLE: { o: 'Kleve', s: ['Nordrhein-Westfalen'] },
  KLZ: { o: 'Klötze', s: ['Sachsen-Anhalt'] },
  KM: { o: 'Kamenz', s: ['Sachsen'] },
  KN: { o: 'Konstanz', s: ['Baden-Württemberg'] },
  KO: { o: 'Koblenz', s: ['Rheinland-Pfalz'] },
  'KÖN': { o: 'Bad Königshofen im Grabfeld', s: ['Bayern'] },
  'KÖT': { o: 'Köthen', s: ['Sachsen-Anhalt'] },
  'KÖZ': { o: 'Bad Kötzting', s: ['Bayern'] },
  KR: { o: 'Krefeld', s: ['Nordrhein-Westfalen'] },
  KRU: { o: 'Krumbach', s: ['Bayern'] },
  KS: { o: 'Kassel', s: ['Hessen'] },
  KT: { o: 'Kitzingen', s: ['Bayern'] },
  KU: { o: 'Kulmbach', s: ['Bayern'] },
  'KÜN': { o: 'Künzelsau', s: ['Baden-Württemberg'] },
  KUS: { o: 'Kusel', s: ['Rheinland-Pfalz'] },
  KW: { o: 'Königs Wusterhausen', s: ['Brandenburg'] },
  KY: { o: 'Kyritz', s: ['Brandenburg'] },
  KYF: { o: 'Kyffhäuser', s: ['Thüringen'] },
  L: { o: 'Leipzig', s: ['Sachsen'] },
  LA: { o: 'Landshut', s: ['Bayern'] },
  LAN: { o: 'Landau an der Isar', s: ['Bayern'] },
  LAU: { o: 'Lauf an der Pegnitz', s: ['Bayern'] },
  LB: { o: 'Ludwigsburg', s: ['Baden-Württemberg'] },
  LBS: { o: 'Bad Lobenstein', s: ['Thüringen'] },
  LBZ: { o: 'Lübz', s: ['Mecklenburg-Vorpommern'] },
  LC: { o: 'Luckau', s: ['Brandenburg'] },
  LD: { o: 'Landau', s: ['Rheinland-Pfalz'] },
  LDK: { o: 'Lahn-Dill-Kreis', s: ['Hessen'] },
  LDS: { o: 'Landkreis Dahme-Spreewald', s: ['Brandenburg'] },
  LE: { o: 'Lemgo', s: ['Nordrhein-Westfalen'] },
  LEO: { o: 'Leonberg', s: ['Baden-Württemberg'] },
  LER: { o: 'Leer', s: ['Niedersachsen'] },
  LEV: { o: 'Leverkusen', s: ['Nordrhein-Westfalen'] },
  LF: { o: 'Laufen', s: ['Bayern'] },
  LG: { o: 'Lüneburg', s: ['Niedersachsen'] },
  LH: { o: 'Lüdinghausen', s: ['Nordrhein-Westfalen'] },
  LI: { o: 'Lindau', s: ['Bayern'] },
  LIB: { o: 'Bad Liebenwerda', s: ['Brandenburg'] },
  LIF: { o: 'Lichtenfels', s: ['Bayern'] },
  LIP: { o: 'Lippe', s: ['Nordrhein-Westfalen'] },
  LK: { o: 'Lübbecke', s: ['Nordrhein-Westfalen'] },
  LL: { o: 'Landsberg am Lech', s: ['Bayern'] },
  LM: { o: 'Limburg an der Lahn', s: ['Hessen'] },
  LN: { o: 'Lübben', s: ['Brandenburg'] },
  'LÖ': { o: 'Lörrach', s: ['Baden-Württemberg'] },
  'LÖB': { o: 'Löbau', s: ['Sachsen'] },
  LOS: { o: 'Landkreis Oder-Spree', s: ['Brandenburg'] },
  LP: { o: 'Lippstadt', s: ['Nordrhein-Westfalen'] },
  LR: { o: 'Lahr/Schwarzwald', s: ['Baden-Württemberg'] },
  LRO: { o: 'Landkreis Rostock', s: ['Mecklenburg-Vorpommern'] },
  LSZ: { o: 'Bad Langensalza', s: ['Thüringen'] },
  LU: { o: 'Ludwigshafen', s: ['Rheinland-Pfalz'] },
  'LÜN': { o: 'Lünen', s: ['Nordrhein-Westfalen'] },
  LUK: { o: 'Luckenwalde', s: ['Brandenburg'] },
  LUP: { o: 'Ludwigslust, Parchim', s: ['Mecklenburg-Vorpommern'] },
  LWL: { o: 'Ludwigslust', s: ['Mecklenburg-Vorpommern'] },
  M: { o: 'München', s: ['Bayern'] },
  MA: { o: 'Mannheim', s: ['Baden-Württemberg'] },
  MAB: { o: 'Marienberg', s: ['Sachsen'] },
  MAI: { o: 'Mainburg', s: ['Bayern'] },
  MAK: { o: 'Marktredwitz', s: ['Bayern'] },
  MAL: { o: 'Mallersdorf-Pfaffenberg', s: ['Bayern'] },
  MB: { o: 'Miesbach', s: ['Bayern'] },
  MC: { o: 'Malchin', s: ['Mecklenburg-Vorpommern'] },
  MD: { o: 'Magdeburg', s: ['Sachsen-Anhalt'] },
  ME: { o: 'Mettmann', s: ['Nordrhein-Westfalen'] },
  MED: { o: 'Meldorf', s: ['Schleswig-Holstein'] },
  MEG: { o: 'Melsungen', s: ['Hessen'] },
  MEI: { o: 'Meißen', s: ['Sachsen'] },
  MEK: { o: 'Mittlerer Erzgebirgskreis', s: ['Sachsen'] },
  MEL: { o: 'Melle', s: ['Niedersachsen'] },
  MER: { o: 'Merseburg', s: ['Sachsen-Anhalt'] },
  MET: { o: 'Mellrichstadt', s: ['Bayern'] },
  MG: { o: 'Mönchengladbach', s: ['Nordrhein-Westfalen'] },
  MGH: { o: 'Bad Mergentheim', s: ['Baden-Württemberg'] },
  MGN: { o: 'Meiningen', s: ['Thüringen'] },
  MH: { o: 'Mülheim', s: ['Nordrhein-Westfalen'] },
  MHL: { o: 'Mühlhausen/Thüringen', s: ['Thüringen'] },
  MI: { o: 'Minden', s: ['Nordrhein-Westfalen'] },
  MIL: { o: 'Miltenberg', s: ['Bayern'] },
  MK: { o: 'Grafschaft Mark Kreis', s: ['Nordrhein-Westfalen'] },
  MKK: { o: 'Main-Kinzig-Kreis', s: ['Hessen'] },
  ML: { o: 'Mansfelder Land', s: ['Sachsen-Anhalt'] },
  MM: { o: 'Memmingen', s: ['Bayern'] },
  MN: { o: 'Mindelheim', s: ['Bayern'] },
  MO: { o: 'Moers', s: ['Nordrhein-Westfalen'] },
  MOD: { o: 'Marktoberdorf', s: ['Bayern'] },
  MOL: { o: 'Mark Brandenburg-Oder', s: ['Brandenburg'] },
  MON: { o: 'Monschau', s: ['Nordrhein-Westfalen'] },
  MOS: { o: 'Mosbach', s: ['Baden-Württemberg'] },
  MQ: { o: 'Merseburg, Querfurt', s: ['Sachsen-Anhalt'] },
  MR: { o: 'Marburg', s: ['Hessen'] },
  MS: { o: 'Münster', s: ['Nordrhein-Westfalen'] },
  MSE: { o: 'Mecklenburgische Seenplatte', s: ['Mecklenburg-Vorpommern'] },
  MSH: { o: 'Mansfelder Land, Südharz', s: ['Sachsen-Anhalt'] },
  MSP: { o: 'Main, Spessart', s: ['Bayern'] },
  MST: { o: 'Mecklenburg-Strelitz', s: ['Mecklenburg-Vorpommern'] },
  MTK: { o: 'Main-Taunus-Kreis', s: ['Hessen'] },
  MTL: { o: 'Mulde', s: ['Sachsen'] },
  MU: { o: 'Münchner Umland', s: ['Bayern'] },
  MUC: { o: 'Muenchen', s: ['Bayern'] },
  'MÜ': { o: 'Mühldorf am Inn', s: ['Bayern'] },
  'MÜB': { o: 'Münchberg', s: ['Bayern'] },
  'MÜL': { o: 'Müllheim im Markgräflerland', s: ['Baden-Württemberg'] },
  'MÜR': { o: 'Müritz', s: ['Mecklenburg-Vorpommern'] },
  MW: { o: 'Mittweida', s: ['Sachsen'] },
  MY: { o: 'Mayen', s: ['Rheinland-Pfalz'] },
  MYK: { o: 'Mayen, Koblenz', s: ['Rheinland-Pfalz'] },
  MZ: { o: 'Mainz', s: ['Rheinland-Pfalz'] },
  MZG: { o: 'Merzig', s: ['Saarland'] },
  N: { o: 'Nürnberg', s: ['Bayern'] },
  NAB: { o: 'Nabburg', s: ['Bayern'] },
  NAI: { o: 'Naila', s: ['Bayern'] },
  NAU: { o: 'Nauen', s: ['Brandenburg'] },
  NB: { o: 'Neubrandenburg', s: ['Mecklenburg-Vorpommern'] },
  ND: { o: 'Neuburg an der Donau', s: ['Bayern'] },
  NDH: { o: 'Nordhausen', s: ['Thüringen'] },
  NE: { o: 'Neuss', s: ['Nordrhein-Westfalen'] },
  NEA: { o: 'Neustadt an der Aisch', s: ['Bayern'] },
  NEB: { o: 'Nebra', s: ['Sachsen-Anhalt'] },
  NEC: { o: 'Neustadt bei Coburg', s: ['Bayern'] },
  NEN: { o: 'Neunburg vorm Wald', s: ['Bayern'] },
  NES: { o: 'Bad Neustadt an der Saale', s: ['Bayern'] },
  NEU: { o: 'Titisee-Neustadt', s: ['Baden-Württemberg'] },
  NEW: { o: 'Neustadt an der Waldnaab', s: ['Bayern'] },
  NF: { o: 'Nordfriesland', s: ['Schleswig-Holstein'] },
  NH: { o: 'Neuhaus am Rennweg', s: ['Thüringen'] },
  NI: { o: 'Nienburg/Weser', s: ['Niedersachsen'] },
  NK: { o: 'Neunkirchen', s: ['Saarland'] },
  NM: { o: 'Neumarkt in der Oberpfalz', s: ['Bayern'] },
  NMB: { o: 'Naumburg', s: ['Sachsen-Anhalt'] },
  NMS: { o: 'Neumünster', s: ['Schleswig-Holstein'] },
  'NÖ': { o: 'Nördlingen', s: ['Bayern'] },
  NOH: { o: 'Nordhorn', s: ['Niedersachsen'] },
  NOL: { o: 'Niederschlesien Oberlausitz', s: ['Sachsen'] },
  NOM: { o: 'Northeim', s: ['Niedersachsen'] },
  NOR: { o: 'Norden', s: ['Niedersachsen'] },
  NP: { o: 'Neuruppin', s: ['Brandenburg'] },
  NR: { o: 'Neuwied am Rhein', s: ['Rheinland-Pfalz'] },
  NT: { o: 'Nürtingen', s: ['Baden-Württemberg'] },
  NU: { o: 'Neu-Ulm', s: ['Bayern'] },
  NVP: { o: 'Nordvorpommern', s: ['Mecklenburg-Vorpommern'] },
  NW: { o: 'Neustadt an der Weinstraße', s: ['Rheinland-Pfalz'] },
  NWM: { o: 'Nordwestmecklenburg', s: ['Mecklenburg-Vorpommern'] },
  NY: { o: 'Niesky', s: ['Sachsen'] },
  NZ: { o: 'Neustrelitz', s: ['Mecklenburg-Vorpommern'] },
  OA: { o: 'Oberallgäu', s: ['Bayern'] },
  OAL: { o: 'Ostallgäu', s: ['Bayern'] },
  OB: { o: 'Oberhausen', s: ['Nordrhein-Westfalen'] },
  OBB: { o: 'Obernburg am Main', s: ['Bayern'] },
  OBG: { o: 'Osterburg', s: ['Sachsen-Anhalt'] },
  OC: { o: 'Oschersleben', s: ['Sachsen-Anhalt'] },
  OCH: { o: 'Ochsenfurt', s: ['Bayern'] },
  OD: { o: 'Bad Oldesloe', s: ['Schleswig-Holstein'] },
  OE: { o: 'Olpe', s: ['Nordrhein-Westfalen'] },
  OF: { o: 'Offenbach', s: ['Hessen'] },
  OG: { o: 'Offenburg', s: ['Baden-Württemberg'] },
  OH: { o: 'Ostholstein', s: ['Schleswig-Holstein'] },
  OHA: { o: 'Osterode am Harz', s: ['Niedersachsen'] },
  'ÖHR': { o: 'Öhringen', s: ['Baden-Württemberg'] },
  OHV: { o: 'Oberhavel', s: ['Brandenburg'] },
  OHZ: { o: 'Osterholz-Scharmbeck', s: ['Niedersachsen'] },
  OK: { o: 'Ohrekreis', s: ['Sachsen-Anhalt'] },
  OL: { o: 'Oldenburg', s: ['Niedersachsen'] },
  OP: { o: 'Opladen', s: ['Nordrhein-Westfalen'] },
  OPR: { o: 'Ostprignitz, Ruppiner Land', s: ['Brandenburg'] },
  OS: { o: 'Osnabrück', s: ['Niedersachsen'] },
  OSL: { o: 'Oberspreewald, Lausitz', s: ['Brandenburg'] },
  OTW: { o: 'Ottweiler', s: ['Saarland'] },
  OVI: { o: 'Oberviechtach', s: ['Bayern'] },
  OVL: { o: 'Obervogtland', s: ['Sachsen'] },
  OZ: { o: 'Oschatz', s: ['Sachsen'] },
  P: { o: 'Potsdam', s: ['Brandenburg'] },
  PA: { o: 'Passau', s: ['Bayern'] },
  PAF: { o: 'Pfaffenhofen an der Ilm', s: ['Bayern'] },
  PAN: { o: 'Pfarrkirchen', s: ['Bayern'] },
  PAR: { o: 'Parsberg', s: ['Bayern'] },
  PB: { o: 'Paderborn', s: ['Nordrhein-Westfalen'] },
  PCH: { o: 'Parchim', s: ['Mecklenburg-Vorpommern'] },
  PE: { o: 'Peine', s: ['Niedersachsen'] },
  PEG: { o: 'Pegnitz', s: ['Bayern'] },
  PF: { o: 'Pforzheim', s: ['Baden-Württemberg'] },
  PI: { o: 'Pinneberg', s: ['Schleswig-Holstein'] },
  PIR: { o: 'Pirna', s: ['Sachsen'] },
  PL: { o: 'Plauen', s: ['Sachsen'] },
  'PLÖ': { o: 'Plön', s: ['Schleswig-Holstein'] },
  PM: { o: 'Potsdam, Mittelmark Brandenburg', s: ['Brandenburg'] },
  PN: { o: 'Pößneck', s: ['Thüringen'] },
  PR: { o: 'Prignitz', s: ['Brandenburg'] },
  'PRÜ': { o: 'Prüm', s: ['Rheinland-Pfalz'] },
  PS: { o: 'Pirmasens', s: ['Rheinland-Pfalz'] },
  PW: { o: 'Pasewalk', s: ['Mecklenburg-Vorpommern'] },
  PZ: { o: 'Prenzlau', s: ['Brandenburg'] },
  QFT: { o: 'Querfurt', s: ['Sachsen-Anhalt'] },
  QLB: { o: 'Quedlinburg', s: ['Sachsen-Anhalt'] },
  R: { o: 'Regensburg', s: ['Bayern'] },
  RA: { o: 'Rastatt', s: ['Baden-Württemberg'] },
  RC: { o: 'Reichenbach im Vogtland', s: ['Sachsen'] },
  RD: { o: 'Rendsburg', s: ['Schleswig-Holstein'] },
  RDG: { o: 'Ribnitz-Damgarten', s: ['Mecklenburg-Vorpommern'] },
  RE: { o: 'Recklinghausen', s: ['Nordrhein-Westfalen'] },
  REG: { o: 'Regen', s: ['Bayern'] },
  REH: { o: 'Rehau', s: ['Bayern'] },
  REI: { o: 'Bad Reichenhall', s: ['Bayern'] },
  RG: { o: 'Riesa, Großenhain', s: ['Sachsen'] },
  RH: { o: 'Roth', s: ['Bayern'] },
  RI: { o: 'Rinteln', s: ['Niedersachsen'] },
  RID: { o: 'Riedenburg', s: ['Bayern'] },
  RIE: { o: 'Riesa', s: ['Sachsen'] },
  RL: { o: 'Rochlitz', s: ['Sachsen'] },
  RM: { o: 'Röbel/Müritz', s: ['Mecklenburg-Vorpommern'] },
  RN: { o: 'Rathenow', s: ['Brandenburg'] },
  RO: { o: 'Rosenheim', s: ['Bayern'] },
  ROD: { o: 'Roding', s: ['Bayern'] },
  ROF: { o: 'Rotenburg an der Fulda', s: ['Hessen'] },
  ROK: { o: 'Rockenhausen', s: ['Rheinland-Pfalz'] },
  ROL: { o: 'Rottenburg an der Laaber', s: ['Bayern'] },
  ROS: { o: 'Rostock', s: ['Mecklenburg-Vorpommern'] },
  ROT: { o: 'Rothenburg ob der Tauber', s: ['Bayern'] },
  ROW: { o: 'Rotenburg', s: ['Niedersachsen'] },
  RP: { o: 'Rhein-Pfalz', s: ['Rheinland-Pfalz'] },
  RS: { o: 'Remscheid', s: ['Nordrhein-Westfalen'] },
  RSL: { o: 'Roßlau', s: ['Sachsen-Anhalt'] },
  RT: { o: 'Reutlingen', s: ['Baden-Württemberg'] },
  RU: { o: 'Rudolstadt', s: ['Thüringen'] },
  'RÜD': { o: 'Rüdesheim am Rhein', s: ['Hessen'] },
  'RÜG': { o: 'Rügen', s: ['Mecklenburg-Vorpommern'] },
  RV: { o: 'Ravensburg', s: ['Baden-Württemberg'] },
  RW: { o: 'Rottweil', s: ['Baden-Württemberg'] },
  RZ: { o: 'Ratzeburg', s: ['Schleswig-Holstein'] },
  S: { o: 'Stuttgart', s: ['Baden-Württemberg'] },
  SAB: { o: 'Saarburg', s: ['Rheinland-Pfalz'] },
  SAD: { o: 'Schwandorf', s: ['Bayern'] },
  'SÄK': { o: 'Bad Säckingen', s: ['Baden-Württemberg'] },
  SAN: { o: 'Stadtsteinach', s: ['Bayern'] },
  SAW: { o: 'Salzwedel', s: ['Sachsen-Anhalt'] },
  SB: { o: 'Saarbrücken', s: ['Saarland'] },
  SBG: { o: 'Strasburg', s: ['Mecklenburg-Vorpommern'] },
  SBK: { o: 'Schönebeck', s: ['Sachsen-Anhalt'] },
  SC: { o: 'Schwabach', s: ['Bayern'] },
  SCZ: { o: 'Schleiz', s: ['Thüringen'] },
  SDH: { o: 'Sondershausen', s: ['Thüringen'] },
  SDL: { o: 'Stendal', s: ['Sachsen-Anhalt'] },
  SDT: { o: 'Schwedt/Oder', s: ['Brandenburg'] },
  SE: { o: 'Bad Segeberg', s: ['Schleswig-Holstein'] },
  SEB: { o: 'Sebnitz', s: ['Sachsen'] },
  SEE: { o: 'Seelow', s: ['Brandenburg'] },
  SEF: { o: 'Scheinfeld', s: ['Bayern'] },
  SEL: { o: 'Selb', s: ['Bayern'] },
  SFB: { o: 'Senftenberg', s: ['Brandenburg'] },
  SFT: { o: 'Staßfurt', s: ['Sachsen-Anhalt'] },
  SG: { o: 'Solingen', s: ['Nordrhein-Westfalen'] },
  SGH: { o: 'Sangerhausen', s: ['Sachsen-Anhalt'] },
  SHA: { o: 'Schwäbisch Hall', s: ['Baden-Württemberg'] },
  SHG: { o: 'Stadthagen', s: ['Niedersachsen'] },
  SHK: { o: 'Saale-Thüringer Holzland-Kreis', s: ['Thüringen'] },
  SHL: { o: 'Suhl', s: ['Thüringen'] },
  SI: { o: 'Siegen', s: ['Nordrhein-Westfalen'] },
  SIG: { o: 'Sigmaringen', s: ['Baden-Württemberg'] },
  SIM: { o: 'Simmern/Hunsrück', s: ['Rheinland-Pfalz'] },
  SK: { o: 'Saalekreis', s: ['Sachsen-Anhalt'] },
  SL: { o: 'Schleswig', s: ['Schleswig-Holstein'] },
  SLE: { o: 'Schleiden', s: ['Nordrhein-Westfalen'] },
  SLF: { o: 'Saalfeld/Saale', s: ['Thüringen'] },
  SLG: { o: 'Bad Saulgau', s: ['Baden-Württemberg'] },
  SLK: { o: 'Salzlandkreis', s: ['Sachsen-Anhalt'] },
  SLN: { o: 'Schmölln', s: ['Thüringen'] },
  SLS: { o: 'Saarlouis', s: ['Saarland'] },
  'SLÜ': { o: 'Schlüchtern', s: ['Hessen'] },
  SLZ: { o: 'Bad Salzungen', s: ['Thüringen'] },
  SM: { o: 'Schmalkalden', s: ['Thüringen'] },
  'SMÜ': { o: 'Schwabmünchen', s: ['Bayern'] },
  SN: { o: 'Schwerin', s: ['Mecklenburg-Vorpommern'] },
  SNH: { o: 'Sinsheim', s: ['Baden-Württemberg'] },
  SO: { o: 'Soest', s: ['Nordrhein-Westfalen'] },
  SOB: { o: 'Schrobenhausen', s: ['Bayern'] },
  SOG: { o: 'Schongau', s: ['Bayern'] },
  SOK: { o: 'Saale-Orla-Kreis', s: ['Thüringen'] },
  'SÖM': { o: 'Sömmerda', s: ['Thüringen'] },
  SON: { o: 'Sonneberg', s: ['Thüringen'] },
  SP: { o: 'Speyer', s: ['Rheinland-Pfalz'] },
  SPB: { o: 'Spremberg', s: ['Brandenburg'] },
  SPN: { o: 'Spree, Lausitzer Neiße', s: ['Brandenburg'] },
  SR: { o: 'Straubing', s: ['Bayern'] },
  SRB: { o: 'Strausberg', s: ['Brandenburg'] },
  SRO: { o: 'Stadtroda', s: ['Thüringen'] },
  ST: { o: 'Steinfurt', s: ['Nordrhein-Westfalen'] },
  STA: { o: 'Starnberg', s: ['Bayern'] },
  STB: { o: 'Sternberg', s: ['Mecklenburg-Vorpommern'] },
  STD: { o: 'Stade', s: ['Niedersachsen'] },
  STE: { o: 'Bad Staffelstein', s: ['Bayern'] },
  STL: { o: 'Stollberg/Erzgeb.', s: ['Sachsen'] },
  STO: { o: 'Stockach', s: ['Baden-Württemberg'] },
  SU: { o: 'Siegburg', s: ['Nordrhein-Westfalen'] },
  SUL: { o: 'Sulzbach-Rosenberg', s: ['Bayern'] },
  'SÜW': { o: 'Südliche Deutsche Weinstraße', s: ['Rheinland-Pfalz'] },
  SW: { o: 'Schweinfurt', s: ['Bayern'] },
  SWA: { o: 'Bad Schwalbach', s: ['Hessen'] },
  SY: { o: 'Syke', s: ['Niedersachsen'] },
  SZ: { o: 'Salzgitter', s: ['Niedersachsen'] },
  SZB: { o: 'Schwarzenberg/Erzgeb.', s: ['Sachsen'] },
  TBB: { o: 'Tauberbischofsheim', s: ['Baden-Württemberg'] },
  TDO: { o: 'Torgau, Delitzsch, Oschatz', s: ['Sachsen'] },
  TE: { o: 'Tecklenburg', s: ['Nordrhein-Westfalen'] },
  TET: { o: 'Teterow', s: ['Mecklenburg-Vorpommern'] },
  TF: { o: 'Teltow, Fläming', s: ['Brandenburg'] },
  TG: { o: 'Torgau', s: ['Sachsen'] },
  TIR: { o: 'Tirschenreuth', s: ['Bayern'] },
  TO: { o: 'Torgau, Oschatz', s: ['Sachsen'] },
  'TÖL': { o: 'Bad Tölz', s: ['Bayern'] },
  TP: { o: 'Templin', s: ['Brandenburg'] },
  TR: { o: 'Trier', s: ['Rheinland-Pfalz'] },
  TS: { o: 'Traunstein', s: ['Bayern'] },
  TT: { o: 'Tettnang', s: ['Baden-Württemberg'] },
  'TÜ': { o: 'Tübingen', s: ['Baden-Württemberg'] },
  TUT: { o: 'Tuttlingen', s: ['Baden-Württemberg'] },
  'ÜB': { o: 'Überlingen', s: ['Baden-Württemberg'] },
  UE: { o: 'Uelzen', s: ['Niedersachsen'] },
  UEM: { o: 'Ueckermünde', s: ['Mecklenburg-Vorpommern'] },
  UFF: { o: 'Uffenheim', s: ['Bayern'] },
  UH: { o: 'Unstrut, Hainich', s: ['Thüringen'] },
  UL: { o: 'Ulm', s: ['Baden-Württemberg'] },
  UM: { o: 'Uckermark', s: ['Brandenburg'] },
  UN: { o: 'Unna', s: ['Nordrhein-Westfalen'] },
  USI: { o: 'Usingen', s: ['Hessen'] },
  V: { o: 'Vogtland', s: ['Sachsen'] },
  VAI: { o: 'Vaihingen an der Enz', s: ['Baden-Württemberg'] },
  VB: { o: 'Vogelsberg', s: ['Hessen'] },
  VEC: { o: 'Vechta', s: ['Niedersachsen'] },
  VER: { o: 'Verden', s: ['Niedersachsen'] },
  VG: { o: 'Vorpommern-Greifswald', s: ['Mecklenburg-Vorpommern'] },
  VIB: { o: 'Vilsbiburg', s: ['Bayern'] },
  VIE: { o: 'Viersen', s: ['Nordrhein-Westfalen'] },
  VIT: { o: 'Viechtach', s: ['Bayern'] },
  VK: { o: 'Völklingen', s: ['Saarland'] },
  VOH: { o: 'Vohenstrauß', s: ['Bayern'] },
  VR: { o: 'Vorpommern-Rügen', s: ['Mecklenburg-Vorpommern'] },
  VS: { o: 'Villingen-Schwenningen', s: ['Baden-Württemberg'] },
  W: { o: 'Wuppertal', s: ['Nordrhein-Westfalen'] },
  WA: { o: 'Waldeck', s: ['Hessen'] },
  WAF: { o: 'Warendorf', s: ['Nordrhein-Westfalen'] },
  WAK: { o: 'Wartburgkreis', s: ['Thüringen'] },
  WAN: { o: 'Wanne', s: ['Nordrhein-Westfalen'] },
  WAR: { o: 'Warburg', s: ['Nordrhein-Westfalen'] },
  WAT: { o: 'Wattenscheid', s: ['Nordrhein-Westfalen'] },
  WB: { o: 'Lutherstadt Wittenberg', s: ['Sachsen-Anhalt'] },
  WBS: { o: 'Worbis', s: ['Thüringen'] },
  WDA: { o: 'Werdau', s: ['Sachsen'] },
  WE: { o: 'Weimar', s: ['Thüringen'] },
  WEL: { o: 'Weilburg', s: ['Hessen'] },
  WEN: { o: 'Weiden', s: ['Bayern'] },
  WER: { o: 'Wertingen', s: ['Bayern'] },
  WES: { o: 'Wesel', s: ['Nordrhein-Westfalen'] },
  WF: { o: 'Wolfenbüttel', s: ['Niedersachsen'] },
  WG: { o: 'Wangen im Allgäu', s: ['Baden-Württemberg'] },
  WHV: { o: 'Wilhelmshaven', s: ['Niedersachsen'] },
  WI: { o: 'Wiesbaden', s: ['Hessen'] },
  WIL: { o: 'Wittlich', s: ['Rheinland-Pfalz'] },
  WIS: { o: 'Wismar', s: ['Mecklenburg-Vorpommern'] },
  WIT: { o: 'Witten', s: ['Nordrhein-Westfalen'] },
  WIZ: { o: 'Witzenhausen', s: ['Hessen'] },
  WK: { o: 'Wittstock/Dosse', s: ['Brandenburg'] },
  WL: { o: 'Winsen', s: ['Niedersachsen'] },
  WLG: { o: 'Wolgast', s: ['Mecklenburg-Vorpommern'] },
  WM: { o: 'Weilheim in Oberbayern', s: ['Bayern'] },
  WMS: { o: 'Wolmirstedt', s: ['Sachsen-Anhalt'] },
  WN: { o: 'Waiblingen', s: ['Baden-Württemberg'] },
  WND: { o: 'St. Wendel', s: ['Saarland'] },
  WO: { o: 'Worms', s: ['Rheinland-Pfalz'] },
  WOB: { o: 'Wolfsburg', s: ['Niedersachsen'] },
  WOH: { o: 'Wolfhagen', s: ['Hessen'] },
  WOL: { o: 'Wolfach', s: ['Baden-Württemberg'] },
  WOR: { o: 'Wolfratshausen', s: ['Bayern'] },
  WOS: { o: 'Schloss Wolfstein', s: ['Bayern'] },
  WR: { o: 'Wernigerode', s: ['Sachsen-Anhalt'] },
  WRN: { o: 'Waren', s: ['Mecklenburg-Vorpommern'] },
  WS: { o: 'Wasserburg am Inn', s: ['Bayern'] },
  WSF: { o: 'Weißenfels', s: ['Sachsen-Anhalt'] },
  WST: { o: 'Westerstede', s: ['Niedersachsen'] },
  WSW: { o: 'Weißwasser', s: ['Sachsen'] },
  WT: { o: 'Waldshut-Tiengen', s: ['Baden-Württemberg'] },
  WTL: { o: 'Wittlage', s: ['Niedersachsen'] },
  WTM: { o: 'Wittmund', s: ['Niedersachsen'] },
  'WÜ': { o: 'Würzburg', s: ['Bayern'] },
  WUG: { o: 'Weißenburg in Bayern', s: ['Bayern'] },
  'WÜM': { o: 'Waldmünchen (mit einem Buchstabendreher)', s: ['Bayern'] },
  WUN: { o: 'Wunsiedel', s: ['Bayern'] },
  WUR: { o: 'Wurzen', s: ['Sachsen'] },
  WW: { o: 'Westerwald', s: ['Rheinland-Pfalz'] },
  WZ: { o: 'Wetzlar', s: ['Hessen'] },
  WZL: { o: 'Stadt Wanzleben', s: ['Sachsen-Anhalt'] },
  Z: { o: 'Zwickau', s: ['Sachsen'] },
  ZE: { o: 'Zerbst/Anhalt', s: ['Sachsen-Anhalt'] },
  ZEL: { o: 'Zell', s: ['Rheinland-Pfalz'] },
  ZI: { o: 'Zittau', s: ['Sachsen'] },
  ZIG: { o: 'Ziegenhain', s: ['Hessen'] },
  ZP: { o: 'Zschopau', s: ['Sachsen'] },
  ZR: { o: 'Zeulenroda', s: ['Thüringen'] },
  ZS: { o: 'Zossen', s: ['Brandenburg'] },
  ZW: { o: 'Zweibrücken', s: ['Rheinland-Pfalz'] },
  ZZ: { o: 'Zeitz', s: ['Sachsen-Anhalt'] },
  OVP: { o: 'Ostvorpommern', s: ['Mecklenburg-Vorpommern'] },
};
